blank_issues_enabled: false
contact_links:
  - name: Questions and Discussion
    url: https://github.com/AndroidIRCx/AndroidIRCx-Flutter/discussions
    about: Ask questions and start discussions.
  - name: Security Reports
    url: https://github.com/AndroidIRCx/AndroidIRCx-Flutter/security/advisories/new
    about: Report security vulnerabilities privately.